Results overview layout
CodeforAustralia/council-emissions-calculator pull request #196
Opened 2022-08-17 06:28 UTC by RCode-Blue

## Overview of the Pull Request:
Edited layout to match other sections in the _Results_ page

## link to Trello card or Github issue
https://trello.com/c/vl2rpehH/322-results-page-has-multiple-layout-methods-which-looks-odd-on-wide-browser-windows

## How Has This Been Tested?
The right-indentation for the _Overview_ section should match that of the other sections:
(Guide borders have been removed from commit)

![image](https://user-images.githubusercontent.com/33863416/185049593-10afadc0-d200-4945-b66e-ddbd2296b604.png)

![image](https://user-images.githubusercontent.com/33863416/185049671-a3a0b2f6-b108-4b57-b8d6-6238f999ccff.png)

## Pull Request Checklist:
- [X] Have you included a link Trello card / Github issue and written sufficient description to help others review your work?
- [X] Is your pull request up-to-date with `main` branch?
- [X] Have you checked That code is well formatted? Did `npx prettier --check .` return no warnings/errors?
- [X] Have you written instructions on how to test that your changes work as expected?
- [X] Have you tested your work thoroughly on your local machine to ensure you are not breaking anything?

2022-08-17 07:59 UTC, hqtan commented
Hi @RCode-Blue ,

It looks like the changes in this PR may have caused the Intro section to be 'misaligned' with the 'Overview' section:
![image](https://user-images.githubusercontent.com/4408259/185065513-bf86c6ce-8dc0-486d-a751-feb4239f83ac.png)

This is currently how it looks like in [prod](https://seechange.codeforaustralia.org/results): 
![image](https://user-images.githubusercontent.com/4408259/185066166-d494e4ac-6ffd-48b7-8133-487ea4a75020.png)

2022-08-17 08:36 UTC, RCode-Blue commented
Sorry @hqtan  my bad. 

Is it better now?

2022-08-17 12:15 UTC, hqtan commented on components/ResultsPageComponents/CommuteDays/CommuteDays.jsx
> +      border="1px dashed red"
please remove the dashed border
```suggestion
```

2022-08-17 12:17 UTC, hqtan requested changes
Hi @RCode-Blue ,

Thx for your PR 🙇🏽 

The changes in this PR are marginal, but I think they do offer a *slight* improvement, so happy to approve it, after the suggested changes are made.

2022-08-18 01:14 UTC, OlaShabalina approved these changes
Well done @RCode-Blue !

2022-08-18 01:32 UTC, hqtan approved these changes
lgtm @RCode-Blue 👍🏽 

let's ship it :shipit:

2022-08-18 01:32 UTC, merged