Carpool travel method selected
CodeforAustralia/council-emissions-calculator pull request #82
Opened 2022-04-05 05:12 UTC by Amutha37

Counter button for carpool travel method on selection  : 

- This button will pop up on the bottom of all the travel method buttons.
- This component will have a break line for mobile version only.
-  The component stay on the  left float for desktop version and centered in mobile version.

2022-04-09 23:12 UTC, hqtan commented
Hi @Amutha37 ,

I cannot see the `Counter` component used in the `TravelMethod` page.
You've created the `Counter` component  in `components/TravelMethodButtons/CarpoolCounter.jsx`, but haven't used in anywhere.

I've tried to test out the `CarpoolCounter` component in the preview deployment of the `TravelMethod` page to test your changes, but it does not appear when I click on the `Carpool` button.
https://council-emissions-calculator-spike-5j7m8gjp8-codeforaustralia.vercel.app/form/TravelMethod

It's possible that I've misunderstood what this PR is meant to do. From the description above, I had assumed that you were implementing the `CarpoolCounter` component.
But with no instructions provided on how to test this PR, and what I should expect to see, it's difficult to understand this PR's intentions.

Can you please provide those details?

2022-04-09 23:16 UTC, hqtan requested changes

2022-04-09 23:16 UTC, hqtan commented on pages/form/TravelMethod.jsx
> +<Collapse in={transportMode === "Carpool"}>
please fix indentation of code here:
```suggestion
        {/* Collapse on carpool selection*/}
        <Collapse in={transportMode === "Carpool"}>
```

2022-04-09 23:16 UTC, hqtan commented on pages/form/TravelMethod.jsx
> +        </Collapse>
Have you forgotten to add the `Counter` component here?
```suggestion
        </Collapse>
        <Counter handleMinus handlePlus count />
```

2022-04-09 23:33 UTC, amu3 commented
To answer  to your request for change , need to have a clear understanding
fron figma. Initially applied on click (carppol) the collapse on carpool.
but looking at figma. it show while carppol is selected with other mode the
counter component stay open.

If this is the case then I have to check the answers from from the object.
At any given time if Carpool and other mode selected the counter remain
open.

This is what I understand from figma.

At the moment the object to save the answers are not ready so I have
temporary commented it.


On Sun, 10 Apr 2022 at 9:16 am, hqtan ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In pages/form/TravelMethod.jsx
> <https://github.com/CodeforAustralia/council-emissions-calculator/pull/82#discussion_r846690047>
> :
>
> > +{/* Collapse on carpool selection*/}
>
> +<Collapse in={transportMode === "Carpool"}>
>
>
> please fix indentation of code here:
> ⬇️ Suggested change
>
> -{/* Collapse on carpool selection*/}
>
> -<Collapse in={transportMode === "Carpool"}>
>
> +        {/* Collapse on carpool selection*/}
>
> +        <Collapse in={transportMode === "Carpool"}>
>
>
> ------------------------------
>
> In pages/form/TravelMethod.jsx
> <https://github.com/CodeforAustralia/council-emissions-calculator/pull/82#discussion_r846690221>
> :
>
> > -            <TravelMethodButtons handleTransportMode={handleTransportMode} />
>
> -
>
> +            <TravelMethodButtons handleTransportMode={handleTransportMode}  />
>
> +{/* Collapse on carpool selection*/}
>
> +<Collapse in={transportMode === "Carpool"}>
>
> +          <Text
>
> +            mb={5}
>
> +            fontSize={[15, 17]}
>
> +            px="20px"
>
> +            py="12px"
>
> +            color="#155724"
>
> +            bg="#D4EDDA"
>
> +          >
>
> +           How many other people would you most likely to carpool with?
>
> +          </Text>
>
> +        </Collapse>
>
>
> Have you forgotten to add the Counter component here?
> ⬇️ Suggested change
>
> -        </Collapse>
>
> +        </Collapse>
>
> +        <Counter handleMinus handlePlus count />
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/CodeforAustralia/council-emissions-calculator/pull/82#pullrequestreview-937184070>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKV7DNGZJHLR4GFDNXQEKXTVEIFWDANCNFSM5SRRQA6A>
> .
> You are receiving this because you were mentioned.Message ID:
> <CodeforAustralia/council-emissions-calculator/pull/82/review/937184070@
> github.com>
>

2022-04-09 23:55 UTC, amu3 commented
On Sun, 10 Apr 2022 at 9:12 am, hqtan ***@***.***> wrote:

> Hi @Amutha37 <https://github.com/Amutha37> ,
>
> I cannot see the Counter component used in the TravelMethod page.
> You've created the Counter component in
> components/TravelMethodButtons/CarpoolCounter.jsx, but haven't used in
> anywhere.
>
> I've tried to test out the CarpoolCounter component in the preview
> deployment of the TravelMethod page to test your changes, but it does not
> appear when I click on the Carpool button.
>
> https://council-emissions-calculator-spike-5j7m8gjp8-codeforaustralia.vercel.app/form/TravelMethod
>
> It's possible that I've misunderstood what this PR is meant to do. From
> the description above, I had assumed that you were implementing the
> CarpoolCounter component.
> But with no instructions provided on how to test this PR, and what I
> should expect to see, it's difficult to understand this PR's intentions.
>
> Can you please provide those details?
>
> — I have made it in a way has described on my PR.
>
     The child component has to be cleared and merged then the parent
component.

I have tested on my side locally uding show state for carpool collpase. It
> is just for testing purpose, once the object amswer is implemented I will
> need to correct this lines of code.
>
  PR # 82 and PR #86 has to be approved and merged . I will at the counter
component that missing.


> Reply to this email directly, view it on GitHub
> <https://github.com/CodeforAustralia/council-emissions-calculator/pull/82#issuecomment-1094139337>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKV7DNEM2RWTN3PGFJ5ZSALVEIFFDANCNFSM5SRRQA6A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***
> com>
>

2022-04-16 04:06 UTC, OlaShabalina approved these changes

2022-04-16 04:08 UTC, merged